## NumPy - III & Pandas

### Agenda:
- Element Wise Mathematical Operations in NumPy
- Dot Product
- Aggregation Functions
- Sort, Search & Counting Functions
- Additional Functions in NumPy
- NumPy Char & Strings
- Pandas Intro

### Element Wise Mathematical Operations in NumPy

In [1]:
import numpy as np

In [2]:
a_list = [1, 2, 3]
b_list = [4, 5, 6]

print(a_list + b_list)

[1, 2, 3, 4, 5, 6]

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]

In [4]:
print(a * b)

[ 4 10 18]

In [5]:
print(a - b)

[-3 -3 -3]

In [6]:
print(b - a)

[3 3 3]

In [7]:
print(b / a)

[4.  2.5 2. ]

In [8]:
print(b // a)

[4 2 2]

In [9]:
print(a / b)

[0.25 0.4  0.5 ]

In [10]:
print(a // b)

[0 0 0]

In [11]:
print(a % b)

[1 2 3]

In [12]:
print(b % a)

[0 1 0]

In [13]:
print(a ** b)

[  1  32 729]

In [14]:
print(b ** a)

[  4  25 216]

### Dot Product
$\sum\limits_{\text{i = 1}}^{\text{n}} a_i  \cdot b_i$

In [15]:
print(a)
print(b)

[1 2 3]
[4 5 6]

In [16]:
# with vectors
print(np.dot(a, b))

32

In [17]:
# with matrices
a_2 = np.array([[1, 2], [3, 4]])
b_2 = np.array([[1, 2], [3, 4]])

In [18]:
print(a_2)
print()
print(b_2)

[[1 2]
 [3 4]]

[[1 2]
 [3 4]]

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} 
\times 
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} 
= 
\begin{bmatrix} (1 \times 1) + (2 \times 3) & (1 \times 2) + (2 \times 4) \\ (3 \times 1) + (4 \times 3) & (3 \times 2) + (4 \times 4) \end{bmatrix} 
= 
\begin{bmatrix} 7 & 10 \\ 15 & 22 \end{bmatrix}
$$

In [19]:
print(np.dot(a_2, b_2))

[[ 7 10]
 [15 22]]

#### Facts of Dot Product

**Fact 1:**

        - if matrix A is of shape (m, n)
        - and matrix B is of shape (n, p)
        - then np.dot(A, b) is of shape (m, p)

**Fact 2:**

        - number of columns in matrix A = number of rows in matrix B

**Fact 3:**

        - let's say if someone is trying to multiply 2 vectors in that case numpy automatically converts one vector into its transpose

In [20]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
b_1 = np.array([[1, 2, 3], [4, 5, 6]])

In [21]:
print(a_1.shape)
print(b_1.shape)

(2, 3)
(2, 3)

In [22]:
print(np.dot(a_1, b_1))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [23]:
print(np.dot(a_1, b_1.T))

[[14 32]
 [32 77]]

In [24]:
print(a_1 @ b_1.T)

[[14 32]
 [32 77]]

In [25]:
# apple, banana, smartphone, toy, furniture

shop_sold_amazon = np.array([
    [100, 200, 20, 30, 5],      # state_1_inventory
    [200, 400, 40, 60, 10]      # state_2_inventory
])

In [26]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200],      # state_1_price
    [34, 12, 1100, 11, 220]      # state_2_price
])

In [27]:
print(price_amazon.T)

[[  30   34]
 [  10   12]
 [1000 1100]
 [  10   11]
 [ 200  220]]

In [28]:
sales = np.dot(shop_sold_amazon, price_amazon.T)

In [29]:
diagonal = np.eye(2, dtype=np.int64)

In [30]:
print(diagonal)

[[1 0]
 [0 1]]

In [31]:
print(sales)

[[26300 29230]
 [52600 58460]]

In [32]:
print(sales * diagonal)

[[26300     0]
 [    0 58460]]

In [33]:
print(np.sum(sales * diagonal))

84760

### Aggregation Functions

In [34]:
array = np.array([1, 2, 3, 4, 5])

In [35]:
print(np.sum(array))

15

In [36]:
print(np.min(array))

1

In [37]:
print(np.max(array))

5

In [38]:
# [1, 2, 3, 4, 5]
print(np.argmax(array))     # it gives the index of the max element

4

In [39]:
array_1 = np.array([1, 2, 100, 45, 450, 2, 5])

In [40]:
# not aggregation function
print(np.argmax(array_1))       # it gives the index of the max element

4

In [41]:
# not aggregation function
print(np.argmin(array_1))       # it gives the index of the min element

0

In [42]:
price_amazon = np.array([
    [30, 10, 1000, 10, 200],      # state_1_price
    [34, 12, 1100, 11, 220]      # state_2_price
])

In [43]:
print(np.sum(price_amazon))

2627

In [44]:
# axis->0: it means sum over rows, keep the columns
print(np.sum(price_amazon, axis=0))

[  64   22 2100   21  420]

In [45]:
# axis->1: it means sum over columns, keep the rows
print(np.sum(price_amazon, axis=1))

[1250 1377]

In [46]:
# array_1 = np.array([1, 2, 100, 45, 450, 2, 5])
print(np.mean(array_1))

86.42857142857143

In [47]:
print(np.mean(price_amazon))

262.7

In [48]:
print(np.mean(price_amazon, axis=1))

[250.  275.4]

In [49]:
print(np.std(price_amazon, axis=1))

[381.73289091 419.66539052]

In [50]:
price_amazon_revised = np.array([
    [30, 10, 1000, 10, 200],
    [34, 12, 1100, 11, 220],
    [34, 12, 1100, 11, 220]
])

In [51]:
print(np.std(price_amazon_revised, axis=1))

[381.73289091 419.66539052 419.66539052]

In [52]:
# cummulative sum
print(np.cumsum(np.array([1, 2, 4, 5, 6, 100])))

[  1   3   7  12  18 118]

In [53]:
print(np.median(price_amazon_revised, axis=1))

[30. 34. 34.]

In [54]:
print(np.var(price_amazon_revised, axis=1))

[145720.   176119.04 176119.04]

In [55]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50))

5.0

### Sort, Search & Counting Functions

In [56]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

In [57]:
print(arr)

[3 6 1 1 1 1 8 2 5 6]

In [58]:
print(f'Sorted : {np.sort(arr)}')
print(f'Sorted Indices : {np.argsort(arr)}')
# Instead of returning the sorted value themseleves, it returns an array of indices that, when used to index the original array, would produce a sorted sequence.

Sorted : [1 1 1 1 2 3 5 6 6 8]
Sorted Indices : [2 3 4 5 7 0 8 1 9 6]

In [59]:
print(f'Insert 4 position : {np.searchsorted(np.sort(arr), 4)}')
print(f'Unique Elements : {np.unique(arr)}')
print(f'Count of Each Element : {np.bincount(arr)}')

# bincount() -> MIN_IDX = 0 & MAX_IDX = 8
# idx = [0 1 2 3 4 5 6 7 8]
# freq = [0 4 1 1 0 1 2 0 1]

Insert 4 position : 6
Unique Elements : [1 2 3 5 6 8]
Count of Each Element : [0 4 1 1 0 1 2 0 1]

In [60]:
arr_new = np.array([3, 6, 1, 1, 1, 1, 1.2, 8, 2, 5, 6])

In [61]:
print(arr_new)

[3.  6.  1.  1.  1.  1.  1.2 8.  2.  5.  6. ]

In [62]:
print(f'Count of Each Element : {np.bincount(arr_new)}')

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

### Additional NumPy Functions

In [63]:
arr_1_d = np.array([1, 2, 3, 4, 5])

for ele in arr_1_d:
    print(ele)

1
2
3
4
5

In [64]:
arr_2_d = np.array([[1, 2], [3, 4]])

for ele in arr_2_d:
    print(ele)

[1 2]
[3 4]

In [65]:
range(0, 11)

range(0, 11)

In [66]:
list(range(0, 11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [67]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
np.arange(8)
# 2 x 4
# 8 x 1
# 2 x 2 x 2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [69]:
arr = np.arange(8).reshape(2, 2, 2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
arr.ndim        # attribute of the class

3

In [71]:
for i in arr:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]

In [72]:
# without changing the shape it will iterate over all values

for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7

In [73]:
a = np.array([1, 2, 3])

In [74]:
b = a       # reference copy

In [75]:
print(id(a))
print(id(b))

4368693744
4368693744

In [76]:
b[0] = 100

In [77]:
b

array([100,   2,   3])

In [78]:
a

array([100,   2,   3])

In [79]:
b = a.copy()

In [80]:
print(id(a))
print(id(b))

4368693744
4368692784

In [81]:
a = np.array([1, 2, 3])

b = a.view()

In [82]:
print(id(a))
print(id(b))

4368694800
4368694704

In [83]:
print(np.shares_memory(a, b))

True

In [84]:
# vstack & hstack

a = np.array([[1, 2]])
b = np.array([[3, 4]])

In [85]:
print(np.vstack((a, b)))

[[1 2]
 [3 4]]

In [86]:
print(np.hstack((a, b)))

[[1 2 3 4]]

In [87]:
print(np.hstack((np.array([[1], [2], [3]]), np.array([[4], [5], [6]]))))

[[1 4]
 [2 5]
 [3 6]]

In [88]:
print(np.vstack((np.array([[1], [2], [3]]), np.array([[4], [5], [6]]))))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

### NumPy Char & Strings

#### np.char.<function_name>()

##### 1. np.char.add()

In [89]:
a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']

##### 2. np.char.multiply()

In [90]:
print(np.char.multiply(a, 2))

['hellohello' 'worldworld']

##### 3. np.char.upper() / np.char.lower() / np.char.capitalize() / np.char.title()

In [91]:
a = np.array(['hello', 'WORLD', 'hello WORLD'])

print(np.char.upper(a))
print(np.char.lower(a))
print(np.char.capitalize(a))
print(np.char.title(a))

['HELLO' 'WORLD' 'HELLO WORLD']
['hello' 'world' 'hello world']
['Hello' 'World' 'Hello world']
['Hello' 'World' 'Hello World']

##### 4. np.char.center()

In [92]:
a = np.array(['hello', 'world'])
print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***world***']

In [93]:
def password(value):
    p = np.array([value[-4:]])
    print(np.char.center(p, 30, fillchar='*'))

In [94]:
password('canwedoitlaterpass')

['*************pass*************']

##### 5. np.char.replace()

In [95]:
arr_str = ['machine_learning', 'data_science']
print(np.char.replace(arr_str, '_', ' '))

['machine learning' 'data science']

##### 6. np.char.split()

In [96]:
print(np.char.split(arr_str, sep='_'))

[list(['machine', 'learning']) list(['data', 'science'])]

In [97]:
split = np.char.split(arr_str, sep='_')

In [98]:
split.ndim

1

##### 7. np.char.find() / np.char.count()

In [99]:
arr_str

['machine_learning', 'data_science']

In [100]:
print(np.char.find(arr_str, 'learn'))

[ 8 -1]

In [101]:
print(np.char.count(arr_str, 'e'))

[2 2]

In [102]:
print(np.char.count(arr_str, 'data'))

[0 1]

### Pandas Intro

In [103]:
import pandas as pd

In [104]:
titanic_dataset_github_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'

In [105]:
df = pd.read_csv(titanic_dataset_github_url)

In [106]:
type(df)

pandas.DataFrame

In [107]:
df.head()       # it shows first five rows of the dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [108]:
df.tail()       # it shows last five rows of the dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [109]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [110]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [111]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [112]:
df[['Name', 'Age']].head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [113]:
df.shape

(891, 12)

In [114]:
dir(df)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'T',
 'Ticket',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']