## Pandas - I

### Agenda:
- Pandas Basics
- Series in Pandas
- DataFrame in Pandas
- Working With Real DataSets
- Loading From Local .csv File

### What is Pandas?
Pandas is an open-source Python library for *data manipulation and analysis*. It gives you powerful, fast, flexible and expressive data structures designed to work with structured data.

It is built on top of NumPy, and its name comes from **"Panel Data"** *(econometrics term for multi-dimensional data)*.

### Why Pandas? What problem does it solve?

#### Before Pandas:

People used raw Python lists, dictionaries or NumPy arrays.

These structures lacked labels, indexing, grouping, join/merge, handling missing data, etc.

Real-world datasets (CSV, JSON, Excel, SQL) are structured in rows and columns $\text{---}$ not arrays.

So Pandas was designed to work like:

📊 Excel + 📚 NumPy + 🗂️ SQL + 🤖 ETL tools $\text{---}$ inside Python

### ⚙️ Where is Pandas used?

| Field | How Pandas Helps |
| :--- | :--- |
| Data Science | Load, clean, explore, transform and model data |
| Machine Learning | Prepare features, preprocesses, manipulate large datasets |
| Finance | Time series, stock prices, trade records |
| Web/Data Analytics | ETL pipelines, server logs, product usage stats |
| Healthcare | Patient records, diagnostics, hospital statistics |

### <img src="https://em-content.zobj.net/source/google/387/brick_1f9f1.png" width="22" alt="Google Brick Emoji"> What does Pandas offer at its core?

| Core Object | Description |
| :--- | :--- |
| <span style="color: #F0D392;">Series</span> | 1D labeled array — like a column |
| <span style="color: #F0D392;">DataFrame</span> | 2D table — like a sheet of Excel or SQL table |
| <span style="color: #F0D392;">Panel</span> (deprecated) | 3D data container (replaced by MultiIndex) |

### 🎁 And Tons of Utilities

- Reading/Writing (CSV, JSON, Excel, SQL, Parquet)
- Powerful slicing/indexing/merging
- GroupBy, pivoting, reshaping
- Time series and date handling
- Missing data handling
- Statistical functions and window operations
- Built-in plotting (with Matplotlib backend)

Think of Pandas like a spreadsheet that you can program, automate and scale $\text{---}$ with the power of Python and NumPy underneath

### Series in Pandas

In [1]:
import pandas as pd

#### 1. Creating Series From Lists

In [2]:
# pd.Series(data, index=None, dtype=None, name=None, copy=False, fastpath=False)
# pd.Series(data)

data = [1, 2, 3, 4, 5, 6]
s1 = pd.Series(data)

In [3]:
print(s1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
s2 = pd.Series(data, index=['a', 'b', 'c', 'd', 'e', 'f'], name='Numbers')

In [5]:
print(s2)

a    1
b    2
c    3
d    4
e    5
f    6
Name: Numbers, dtype: int64

#### 2. Creating Series From Dictionaries

In [6]:
data = {'a': 1, 'b': 2, 'c': 3}
s3 = pd.Series(data)
print(s3)

a    1
b    2
c    3
dtype: int64

#### 3. Creating Series From NumPy Array

In [7]:
import numpy as np

In [8]:
arr = np.array([5, 10, 15])
s4 = pd.Series(arr, index=['x', 'y', 'z'])
print(s4)

x     5
y    10
z    15
dtype: int64

#### 4. Series Attributes & Properties

In [9]:
s5 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'], name='Scores')

In [10]:
print(s5)
print(s5.index)     # Index object
print(s5.values)    # NumPy array of values
print(s5.dtype)     # Data type
print(s5.name)      # Name of the Series
print(s5.shape)
print(type(s5.shape))

a    10
b    20
c    30
d    40
Name: Scores, dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='str')
[10 20 30 40]
int64
Scores
(4,)
<class 'tuple'>

#### 5. Series Indexing & Access

##### 5.1. Positional Indexing

In [11]:
# [10 20 30 40]
print(s5.values[0])
print(s5.values[3])
print(s5.values[4])

10
40

IndexError: index 4 is out of bounds for axis 0 with size 4

##### iloc
iloc gets rows (and/or columns) at integer locations.

In [12]:
print(s5.iloc[0])

10

In [13]:
print(s5.iloc[1:3])

b    20
c    30
Name: Scores, dtype: int64

##### 5.2. Label-based Indexing
loc gets rows (and/or columns) with particular labels.

In [14]:
# Pandas resolves s2[0] in the following order:

# Check if 0 is a label in the index
# → If yes, return by label

# If not, and if the index is not integer-based, then treat 0 as a position
# → Return item at index position 0 (first element)

# FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behaviour). To access a value by position, use `ser.iloc[pos]`

print(s5[0])

KeyError: 0

In [15]:
print(s5['a'])

10

In [16]:
print(s5['b'])

20

In [17]:
# .loc[] uses the label/index name, not position.

In [18]:
print(s5[['b', 'd']])

b    20
d    40
Name: Scores, dtype: int64

In [19]:
print(s5.loc[['b', 'd']])

b    20
d    40
Name: Scores, dtype: int64

In [20]:
s6 = pd.Series([10, 20, 30, 40])

In [21]:
s6.iloc[[1, 2]]

1    20
2    30
dtype: int64

In [22]:
s6.iloc[1:3]

1    20
2    30
dtype: int64

In [23]:
s6.loc[[1, 2]]

1    20
2    30
dtype: int64

### DataFrame in Pandas

#### What is a DataFrame?
A DataFrame is a 2D labeled data structure with columns of potentially different types, just like a spreadsheet or SQL table.

Think of it like:
- A dict of Series
- Or a table with rows and columns

It is the core structure of pandas used for:
- Reading, cleaning, transforming, analyzing and exporting data

#### Why DataFrame?
Real-world data is usually tabular (e.g., CSV, Excel, SQL)

Rows = records

Columns = features

It supports label-based indexing, automatic alignment, missing data handling, grouping, aggregation and more
| Concept | Real-Life Analogy |
| :--- | :--- |
| <span style="color: #F0D392;"> DataFrame </span> | Excel sheet or database table |
| <span style="color: #F0D392;"> Series </span> | One column of that sheet |
| Index | Row number or ID |
| Columns | Named headers |

#### 1. Creating a DataFrame using A Dictionary of Lists

In [24]:
data = {
    'Name' : ['Hemanth', 'Aditya', 'Rajbeer'],
    'Age' : [30, 31, 32],
    'City' : ['Delhi', 'Mumbai', 'Bengaluru']
}

In [25]:
df = pd.DataFrame(data)

In [26]:
print(df)

      Name  Age       City
0  Hemanth   30      Delhi
1   Aditya   31     Mumbai
2  Rajbeer   32  Bengaluru

In [27]:
df

      Name  Age       City
0  Hemanth   30      Delhi
1   Aditya   31     Mumbai
2  Rajbeer   32  Bengaluru

#### 2. Creating a DataFrame using A List of Dictionaries

In [28]:
data = [
    {'Name' :  'Hemanth', 'Age' : 30, 'City' : 'Delhi'},
    {'Name' :  'Aditya', 'Age' : 31, 'City' : 'Mumbai'},
    {'Name' :  'Rajbeer', 'Age' : 32, 'City' : 'Bengaluru'}
]

In [29]:
df = pd.DataFrame(data)
df

      Name  Age       City
0  Hemanth   30      Delhi
1   Aditya   31     Mumbai
2  Rajbeer   32  Bengaluru

#### 3. Creating a DataFrame using NumPy Arrays (if all columns are of the same type)

In [30]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
df = pd.DataFrame(arr, columns=['A', 'B'])
df

   A  B
0  1  2
1  3  4
2  5  6

#### 4. Accessing Data from DataFrame

In [31]:
data = {
    'Name' : ['Hemanth', 'Aditya', 'Rajbeer'],
    'Age' : [30, 31, 32],
    'City' : ['Delhi', 'Mumbai', 'Bengaluru']
}

df = pd.DataFrame(data)

In [32]:
print(df['Name'])       # Series (a column)
print(30 * '=')
print(df[['Name', 'Age']])      # DataFrame with 2 columns
print(30 * '=')
print(df.iloc[0])       # Row by integer index label or position
print(30 * '=')
print(df.loc[0])        # Row by index label

0    Hemanth
1     Aditya
2    Rajbeer
Name: Name, dtype: str
==============================
      Name  Age
0  Hemanth   30
1   Aditya   31
2  Rajbeer   32
==============================
Name    Hemanth
Age          30
City      Delhi
Name: 0, dtype: object
==============================
Name    Hemanth
Age          30
City      Delhi
Name: 0, dtype: object

### Working With Real Datasets

In [33]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'

# https://github.com/mwaskom/seaborn-data/tree/master
iris_dataset_github_url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv'

# kaggle
kaggle_link = 'https://www.kaggle.com/datasets/yasserh/titanic-dataset/data'

In [34]:
df = pd.read_csv(titanic_dataset_github_url)
df.head()       # prints the first 5 records of the dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
display(df.head(3))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [36]:
df.columns        # prints all the column headers of the dataset

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [37]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [38]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [39]:
df.loc[0]       # gives the first row data

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [40]:
df.loc[0]['Name']

'Braund, Mr. Owen Harris'

In [41]:
df.loc[0, 'Name']

'Braund, Mr. Owen Harris'

In [42]:
df.iloc[0]      # displays the first record

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [43]:
df.iloc[:5]     # displays the first 5 records of the dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [44]:
df.iloc[0, 3]

'Braund, Mr. Owen Harris'

In [45]:
df.iloc[0:5, 3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

### Loading From Local .csv File

In [46]:
titanic_dataset_local_url = 'titanic.csv'
df = pd.read_csv(titanic_dataset_local_url)

In [47]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### 5. Conditional Selection (Boolean Indexing)

In [48]:
# Passengers older than 70
df['Age'] > 70      # boolean index of passengers > 70 (True) else False

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [49]:
df[df['Age'] > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [50]:
older_passengers = df[df['Age'] > 70]
display(older_passengers.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [51]:
older_passengers.shape

(5, 12)

In [52]:
older_passengers.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 96 to 851
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  5 non-null      int64
 1   Survived     5 non-null      int64
 2   Pclass       5 non-null      int64
 3   Name         5 non-null      str
 4   Sex          5 non-null      str
 5   Age          5 non-null      float64
 6   SibSp        5 non-null      int64
 7   Parch        5 non-null      int64
 8   Ticket       5 non-null      str
 9   Fare         5 non-null      float64
 10  Cabin        2 non-null      str
 11  Embarked     5 non-null      str
dtypes: float64(2), int64(5), str(5)
memory usage: 520.0 bytes

In [53]:
older_passengers.describe()

       PassengerId  Survived    Pclass        Age  SibSp  Parch       Fare
count     5.000000  5.000000  5.000000   5.000000    5.0    5.0   5.000000
mean    438.200000  0.200000  1.800000  73.300000    0.0    0.0  25.936680
std     328.292096  0.447214  1.095445   3.993745    0.0    0.0  18.086844
min      97.000000  0.000000  1.000000  70.500000    0.0    0.0   7.750000
25%     117.000000  0.000000  1.000000  71.000000    0.0    0.0   7.775000
50%     494.000000  0.000000  1.000000  71.000000    0.0    0.0  30.000000
75%     631.000000  0.000000  3.000000  74.000000    0.0    0.0  34.654200
max     852.000000  1.000000  3.000000  80.000000    0.0    0.0  49.504200

In [54]:
older_passengers['PassengerId'].describe()

count      5.000000
mean     438.200000
std      328.292096
min       97.000000
25%      117.000000
50%      494.000000
75%      631.000000
max      852.000000
Name: PassengerId, dtype: float64

In [55]:
# Females who survived
df[(df['Survived'] == 1) & (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [56]:
# get Name and Age Females who survived
female_survivors_subset = df[(df['Survived'] == 1) & (df['Sex'] == 'female')][['Name', 'Age']]
female_survivors_subset.head()

                                                Name   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

In [57]:
# get Name and Age Females who survived using loc
# df.loc[labels, ['Name', 'Age']]

df.loc[(df['Survived'] == 1) & (df['Sex'] == 'female'), ['Name', 'Age']]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

#### 6. Slicing Rows and Columns Together

In [58]:
# Rows 0 to 4, only Name and Age
df.loc[0:4, ['Name', 'Age']]

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [59]:
# first 3 rows and first 2 columns

df.iloc[:3, :2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1

In [60]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [61]:
# first 3 rows and column Name as the first column and then Survived

df.loc[:2, ['Name', 'Survived']]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

In [62]:
df.iloc[:3, [3, 1]]

                                                Name  Survived
0                            Braund, Mr. Owen Harris         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...         1
2                             Heikkinen, Miss. Laina         1

#### 7. Set Index (Optional)

In [63]:
df_by_passenger_id = df.set_index('PassengerId')

In [64]:
df_by_passenger_id.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [65]:
df_by_passenger_id.iloc[0]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [66]:
df_by_passenger_id.loc[0]

KeyError: 0

In [67]:
df_by_passenger_id.loc[1]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [68]:
df_by_passenger_id = df_by_passenger_id.reset_index()

In [69]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

## Assignment

    - Download below csv using python

            - 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'

    - Create a class

    - Create an object of that class and call the obj.download(URL, path_to_download='data')

    - You are not supposed to use pandas or numpy
    
    - Only use Python and libraries like request or other url based libraries