## Pandas - III

### Agenda:
- Pandas
    - Working with Text Data in Pandas (continued)
    - Categorical Data in Pandas
    - Date Functionality in Pandas

- Regex

- Git
    - GitHub

### Pandas

In [1]:
import pandas as pd

In [2]:
titanic_dataset_github_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'
df = pd.read_csv(titanic_dataset_github_url)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### Working with Text Data in Pandas

##### Replacing a Substring with a Particular String

In [4]:
df['Name'].str.replace('Mr.', 'Sir', regex=False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [5]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [6]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [7]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

##### Find Index of a Particular Substring

In [8]:
start = df.loc[1, 'Name'].find('(')

In [9]:
end = df.loc[1, 'Name'].find(')')

In [10]:
df.loc[1, 'Name'][0 : start] + df.loc[1, 'Name'][end+1 : ]

'Cumings, Mrs. John Bradley '

In [11]:
def remove_substring(name):
    start = name.find('(')
    end = name.find(')')
    new_name = name[ : start] + name[(end + 1) : ]
    new_name = new_name.strip()
    return new_name


df['Name_Trimmed'] = df['Name'].apply(remove_substring)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_Trimmed
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Mr. Owen HarriBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. LainHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William HenrAllen, Mr. William Henry"

In [12]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [13]:
df['Name_Trimmed'].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_Trimmed, dtype: str

In [14]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [15]:
df.loc[1, 'Name_Trimmed']

'Cumings, Mrs. John Bradley'

##### Replace substrings with regex : Regular Expression

In [16]:
# . -> match any character
# * -> 0 or more characters

df['Name'].str.replace(r'\(.*\)', 'HELLO', regex=True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

| Part | Meaning |
| :--- | :--- |
| `r` | raw string literal $\text{---}$ tells Python **not to interpret** `\` as escape |
| `\(` | Escaped `(` $\text{---}$ matches a literal opening parenthesis |
| `.*`| Dot `.` matches **any character** and `*` means **zero or more** |
| `\)` | Escaped `)` $\text{---}$ matches a literal closing parenthesis |

### Regex

In [17]:
import re

In [18]:
def is_valid_email(email):
    """
    Validates if the provided email meets standard regex patterns.
    Returns True if valid, False otherwise.
    """
    # Regex pattern for standard email validation
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # re.fullmatch ensures the entire string matches the pattern
    return bool(re.fullmatch(pattern, email))

In [19]:
# Example usage
test_emails = [
    "user@example.com",
    "first.last@subdomain.domain.org",
    "invalid-email.com",
    "user@@example.com",
    "user@.com",
    "hello@ghail@abc.com"
]

for email in test_emails:
    if is_valid_email(email):
        print(f"'{email}' is a valid email address.")
    else:
        print(f"'{email}' is an invalid email address.")

'user@example.com' is a valid email address.
'first.last@subdomain.domain.org' is a valid email address.
'invalid-email.com' is an invalid email address.
'user@@example.com' is an invalid email address.
'user@.com' is an invalid email address.
'hello@ghail@abc.com' is an invalid email address.

##### Split & Access Elements

In [20]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [21]:
df['Name'].str.split(',')[0]

['Braund', ' Mr. Owen Harris']

In [22]:
df['Name'].str.split()[0]

['Braund,', 'Mr.', 'Owen', 'Harris']

In [23]:
df['Name'].str.split().str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

In [24]:
df['Name'].str.split()[0][0]

'Braund,'

##### Strip Spaces

In [25]:
df['Name'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [26]:
df['Name'].str.lstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [27]:
df['Name'].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

##### Find Position of Substring

In [28]:
df['Name'].str.find('Mr')

0       8
1       9
2      -1
3      10
4       7
       ..
886    -1
887    -1
888    -1
889     6
890     8
Name: Name, Length: 891, dtype: int64

In [29]:
# 'Miss'
# 'Count passengers with Miss in name'

count = df['Name'].str.contains('Miss').sum()
print(f'Number of \'Miss\' : {count}')

Number of 'Miss' : 182

In [30]:
data = {
    'Name' : [
        'John Doe', 'Jane Smith', 'Emily Johnson',
        'Robert Brown', 'Anna-Marie Lee'
    ],
    'Email' : [
        'john@example.com', 'jane.smith@work.org',
        'emily_j@data.net', 'robertb@yahoo.com',
        'anna.lee@company.co'
    ]
}

df = pd.DataFrame(data)

In [31]:
df.head()

             Name                Email
0        John Doe     john@example.com
1      Jane Smith  jane.smith@work.org
2   Emily Johnson     emily_j@data.net
3    Robert Brown    robertb@yahoo.com
4  Anna-Marie Lee  anna.lee@company.co

In [32]:
df['Name'].str.pad(width=20, side='left', fillchar='-')

0    ------------John Doe
1    ----------Jane Smith
2    -------Emily Johnson
3    --------Robert Brown
4    ------Anna-Marie Lee
Name: Name, dtype: str

#### Categorical Data in Pandas

##### 📌 What is Categorical Data?
Categorical data is textual or labeled data that represents discrete categories.

In [33]:
class_data = {
    'Name' : ['A', 'B', 'C', 'D'],
    'Groups' : ['G1', 'G2', 'G3', 'G4']
}

In [34]:
class_df = pd.DataFrame(class_data)

In [35]:
class_df

  Name Groups
0    A     G1
1    B     G2
2    C     G3
3    D     G4

In [36]:
# class_df['Groups'] > G4

In [37]:
# G3, G1, G2, G4 --> Higher to Lower
# class_df['Groups'] > G4
# G1 > G4 --> True

In [38]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [39]:
class_df['Group_cat'] = pd.Categorical(
    class_df['Groups'],
    categories=['G4', 'G2', 'G1', 'G3'],     # Custom order : ascending order
    ordered=True
)

In [40]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Groups     4 non-null      str
 2   Group_cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [41]:
class_df

  Name Groups Group_cat
0    A     G1        G1
1    B     G2        G2
2    C     G3        G3
3    D     G4        G4

In [42]:
class_df['Group_cat'].cat.categories

Index(['G4', 'G2', 'G1', 'G3'], dtype='str')

In [43]:
class_df['Group_cat'] > 'G4'

0     True
1     True
2     True
3    False
Name: Group_cat, dtype: bool

In [44]:
df = pd.read_csv(titanic_dataset_github_url)

In [45]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [46]:
df['Embarked'].unique()     # the port where a passenger boarded the ship, indicated by a single-letter code
# C (Cherbourg)
# Q (Queenstown)
# S (Southampton)

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [47]:
df['Embarked'] = df['Embarked'].fillna('N')

In [48]:
df['Embarked'].unique()
# C (Cherbourg) --> 1000000
# Q (Queenstown) --> 5000000
# S (Southampton) --> 100000
# N --> Not provided --> 000000

# N, S, C, Q

# Find all passengers > 100000 (S)

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [49]:
df['Embarked_auto_cat'] = df['Embarked'].astype('category')

In [50]:
df['Embarked_auto_cat'].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [51]:
df['Embarked_cust_cat'] = pd.Categorical(
    df['Embarked'],
    categories=['N', 'S', 'C', 'Q'],
    ordered=True
)

In [52]:
df['Embarked_cust_cat'].cat.categories

Index(['N', 'S', 'C', 'Q'], dtype='str')

In [53]:
df['Embarked_cust_cat'] > 'S'

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889     True
890     True
Name: Embarked_cust_cat, Length: 891, dtype: bool

In [54]:
df['Embarked_cust_cat'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_cust_cat, dtype: category
Categories (4, str): ['N' < 'S' < 'C' < 'Q']

In [55]:
df['Embarked_cust_cat'].cat.codes.head()

0    1
1    2
2    1
3    1
4    1
dtype: int8

In [56]:
# df['Sex']

# Convert the values of Sex column and encode them in 0 & 1

df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [57]:
df['Sex_Encoded'] = df['Sex'].apply(lambda gender: 0 if gender=='female' else 1)

In [58]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Embarked_auto_cat,Embarked_cust_cat,Sex_Encoded
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,S,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,S,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,S,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,S,S,1

#### Date Functionality in Pandas

In [59]:
df = pd.DataFrame({
    'event' : ['Concert', 'Conference', 'Wedding'],
    'date' : ['2025-01-01', '2025-03-15', '2025-07-20']
})

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [61]:
df

        event        date
0     Concert  2025-01-01
1  Conference  2025-03-15
2     Wedding  2025-07-20

In [62]:
df['date_pandas'] = pd.to_datetime(df['date'])

In [63]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [64]:
df

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15
2     Wedding  2025-07-20  2025-07-20

In [65]:
df['date_pandas'].dt.year

0    2025
1    2025
2    2025
Name: date_pandas, dtype: int32

In [66]:
df['date_pandas'].dt.month

0    1
1    3
2    7
Name: date_pandas, dtype: int32

In [67]:
df['date_pandas'].dt.month_name()

0    January
1      March
2       July
Name: date_pandas, dtype: str

In [68]:
df['date_pandas'].dt.day

0     1
1    15
2    20
Name: date_pandas, dtype: int32

In [69]:
df['date_pandas'].dt.weekday

0    2
1    5
2    6
Name: date_pandas, dtype: int32

In [70]:
df['date_pandas'].dt.day_name()

0    Wednesday
1     Saturday
2       Sunday
Name: date_pandas, dtype: str

In [71]:
df[df['date_pandas'] > '2025-04-01']

     event        date date_pandas
2  Wedding  2025-07-20  2025-07-20

In [72]:
df[df['date_pandas'].between('2025-01-01', '2025-06-01')]

        event        date date_pandas
0     Concert  2025-01-01  2025-01-01
1  Conference  2025-03-15  2025-03-15

##### Creating Datetime Ranges
Other frequencies:

'ME' $\rightarrow$ month end

'MS' $\rightarrow$ month start

'W' $\rightarrow$ weekly

'H', 'T', 'S' $\rightarrow$ hour, minute, second

In [73]:
pd.date_range(start='2026-02-01', end='2026-02-10', freq='D')

DatetimeIndex(['2026-02-01', '2026-02-02', '2026-02-03', '2026-02-04',
               '2026-02-05', '2026-02-06', '2026-02-07', '2026-02-08',
               '2026-02-09', '2026-02-10'],
              dtype='datetime64[us]', freq='D')

In [74]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='ME')

DatetimeIndex(['2024-01-31', '2024-02-29'], dtype='datetime64[us]', freq='ME')

In [75]:
pd.date_range(start='2024-01-01', end='2024-03-10', freq='MS')

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01'], dtype='datetime64[us]', freq='MS')

##### Date Arithmetic

In [76]:
df['next_week'] = df['date_pandas'] + pd.Timedelta(days=7)

In [77]:
pd.Timedelta(days=7)

Timedelta('7 days 00:00:00')

In [78]:
df

        event        date date_pandas  next_week
0     Concert  2025-01-01  2025-01-01 2025-01-08
1  Conference  2025-03-15  2025-03-15 2025-03-22
2     Wedding  2025-07-20  2025-07-20 2025-07-27

In [79]:
df['days_to_event'] = df['date_pandas'] - pd.Timestamp.today()

In [80]:
df

        event        date date_pandas  next_week              days_to_event
0     Concert  2025-01-01  2025-01-01 2025-01-08 -618 days +11:34:50.020878
1  Conference  2025-03-15  2025-03-15 2025-03-22 -545 days +11:34:50.020878
2     Wedding  2025-07-20  2025-07-20 2025-07-27 -418 days +11:34:50.020878

### Git

- `Git` is a tool to manage `our code`
- Just like `uv` manages `project + dependencies`
- `Git` is a *code version tool*

#### GitHub
- It is a central repository of your code + Git
- With this we can store our projects on web
- Also we can collaborate with our team members