## Pandas - III

### Agenda:
- Pandas
- Git

### Pandas

In [1]:
import pandas as pd

In [2]:
titanic_dataset_github_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'
df = pd.read_csv(titanic_dataset_github_url)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df['Name'].str.replace('Mr.', 'Sir', regex=False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [5]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [6]:
df.loc[1]['Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [7]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [8]:
start = df.loc[1, 'Name'].find('(')

In [9]:
end = df.loc[1, 'Name'].find(')')

In [10]:
df.loc[1, 'Name'][0 : start] + df.loc[1, 'Name'][end+1 : ]

'Cumings, Mrs. John Bradley '

In [11]:
def remove_substring(name):
    start = name.find('(')
    end = name.find(')')
    new_name = name[ : start] + name[(end + 1) : ]
    new_name = new_name.strip()
    return new_name


df['Name_Trimmed'] = df['Name'].apply(remove_substring)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Name_Trimmed
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,"Braund, Mr. Owen HarriBraund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,"Cumings, Mrs. John Bradley"
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,"Heikkinen, Miss. LainHeikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,"Futrelle, Mrs. Jacques Heath"
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,"Allen, Mr. William HenrAllen, Mr. William Henry"

In [12]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [13]:
df['Name_Trimmed'].head()

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_Trimmed, dtype: str

In [14]:
df.loc[1, 'Name']

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [15]:
df.loc[1, 'Name_Trimmed']

'Cumings, Mrs. John Bradley'

In [16]:
# Replace substrings with regex : Regular Expression

# . -> match any character
# * -> 0 or more characters

df['Name'].str.replace(r'\(.*\)', 'HELLO', regex=True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

| Part | Meaning |
| :--- | :--- |
| `r` | raw string literal $\text{---}$ tells Python **not to interpret** `\` as escape |
| `\(` | Escaped `(` $\text{---}$ matches a literal opening parenthesis |
| `.*`| Dot `.` matches **any character** and `*` means **zero or more** |
| `\)` | Escaped `)` $\text{---}$ matches a literal closing parenthesis |

In [17]:
import re

In [18]:
def is_valid_email(email):
    """
    Validates if the provided email meets standard regex patterns.
    Returns True if valid, False otherwise.
    """
    # Regex pattern for standard email validation
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    
    # re.fullmatch ensures the entire string matches the pattern
    return bool(re.fullmatch(pattern, email))

In [19]:
# Example usage
test_emails = [
    "user@example.com",
    "first.last@subdomain.domain.org",
    "invalid-email.com",
    "user@@example.com",
    "user@.com",
    "hello@ghail@abc.com"
]

for email in test_emails:
    if is_valid_email(email):
        print(f"'{email}' is a valid email address.")
    else:
        print(f"'{email}' is an invalid email address.")

'user@example.com' is a valid email address.
'first.last@subdomain.domain.org' is a valid email address.
'invalid-email.com' is an invalid email address.
'user@@example.com' is an invalid email address.
'user@.com' is an invalid email address.
'hello@ghail@abc.com' is an invalid email address.