## Pandas-II

### Agenda:
- Are Subsets views or copies in Pandas?
- set_index v/s reindex
- Iteration in Pandas
- Add Column with Custom Logic
- Sorting in Pandas
- Working with Text Data in Pandas

### Are Subsets views or copies in Pandas?

In pandas, whether you get a view (linked to original DataFrame) or a copy (independent) depends on how you slice or filter $\text{---}$ and it's not always obvious. 

- .iloc always returns a copy (safe, independent subset)
- .loc may return a view (especially if indexing on labels)

        subset = df.loc[df['Sex'] == 'male']
        This is like the earlier filtering - might be a view.

        so..
        subset = df.loc[df['Sex'] == 'male'].copy()
        
| Situation | View or Copy? | Should you use <span style="color: #F0D392;">.copy()?</span> |
| :--- | :--- | :--- |
| <span style="color: #F0D392;">.iloc[]</span> slicing | Mostly Copy | Optional |
| <span style="color: #F0D392;">.loc[]</span> slicing | May be View | Recommended |
| Filtering with condition <span style="color: #F0D392;">df[...]</span> | May be View | Recommended |
| You plan to modify the subset | Use <span style="color: #F0D392;">.copy()</span> | YES |

In [1]:
import pandas as pd

In [2]:
titanic_dataset_github_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv'
df = pd.read_csv(titanic_dataset_github_url)

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df_by_passenger_id = df.set_index('PassengerId')

In [5]:
df_by_passenger_id.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df_by_name = df.set_index('Name')

In [7]:
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
print(df_by_name.loc['Allen, Miss. Elisabeth Walton'])

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [9]:
df_by_name = df_by_name.reset_index()

In [10]:
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
# instead of below

# subset = df[df['Sex'] == 'male']
# subset['Age'] += 1

# SettingWithCopyWarning: A value is trying to be set on a copy of a slice of a DataFrame.

In [12]:
subset = df[df['Sex'] == 'male'].copy()
subset['Age'] += 1

In [13]:
df[df['Sex'] == 'male'].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [14]:
subset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S

### Set Index v/s Re-Index

| Features | <span style="color: #F0D392;">set_index()</span> | <span style="color: #F0D392;">reindex()</span> |
| :--- | :--- | :--- |
| What it does? | **Moves a column** to become the index | **Changes the row/column labels** of a DataFrame |
| Main Use Case | Change the row labels using existing column | Match to new labels, add/remove/reorder rows/columns |
| Affects index | Yes $\text{--}$ creates a **new index from a column** | Yes $\text{--}$ but just **remaps or aligns to new index** |
| Adds NaNs? | No $\text{--}$ only restructures | Yes $\text{--}$ can insert NaNs for new labels |

In [15]:
# NaN -> Not a Number

#### 1. set_index $\text{---}$ Use a column as the new index

In [16]:
df_by_name = df.set_index('Name')
print(df_by_name.loc['Allen, Miss. Elisabeth Walton'])      # Now, 'Name' is index

PassengerId         731
Survived              1
Pclass                1
Sex              female
Age                29.0
SibSp                 0
Parch                 0
Ticket            24160
Fare           211.3375
Cabin                B5
Embarked              S
Name: Allen, Miss. Elisabeth Walton, dtype: object

In [17]:
df_by_name.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
df_by_name = df_by_name.reset_index()

In [19]:
df_by_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

#### 2. reindex() $\text{---}$ Conform to a new index/column structure

In [20]:
sales_jan = pd.DataFrame({
    'Sales' : [250, 400, 300]
}, index=['Store_A', 'Store_B', 'Store_C'])

sales_jan

         Sales
Store_A    250
Store_B    400
Store_C    300

In [21]:
sales_feb = pd.DataFrame({
    'Sales' : [260, 310]
}, index=['Store_A', 'Store_C'])

sales_feb

         Sales
Store_A    260
Store_C    310

❌ Problem: Indexes are mismatched!

You cannot safely do operations like subtraction or direct comparison unless indexes are aligned.

✅ 🛠️ Solution: Use reindex() to align!

In [22]:
common_index = sales_jan.index

print(common_index)

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

In [23]:
sales_feb_aligned = sales_feb.reindex(common_index)

sales_feb_aligned

         Sales
Store_A  260.0
Store_B    NaN
Store_C  310.0

In [24]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A    10.0
Store_B     NaN
Store_C    10.0
Name: Sales, dtype: float64

In [25]:
sales_feb_aligned = sales_feb.reindex(common_index, fill_value=0)

sales_feb_aligned

         Sales
Store_A    260
Store_B      0
Store_C    310

In [26]:
sales_diff = sales_feb_aligned['Sales'] - sales_jan['Sales']

sales_diff

Store_A     10
Store_B   -400
Store_C     10
Name: Sales, dtype: int64

#### For Column

In [27]:
source_a = pd.DataFrame({
    'Product' : ['Laptop', 'Tablet', 'Phone'],
    'Price' : [1000, 500, 800],
    'Stock' : [30, 50, 100]
})

source_a

  Product  Price  Stock
0  Laptop   1000     30
1  Tablet    500     50
2   Phone    800    100

In [28]:
source_b = pd.DataFrame({
    'Price' : [980, 520, 810],
    'Product' : ['Laptop', 'Tablet', 'Phone'] 
})

source_b

   Price Product
0    980  Laptop
1    520  Tablet
2    810   Phone

In [29]:
aligned_b = source_b.reindex(columns=source_a.columns, fill_value=0)

aligned_b

  Product  Price  Stock
0  Laptop    980      0
1  Tablet    520      0
2   Phone    810      0

In [30]:
stock_diff = source_a['Stock'] - aligned_b['Stock']

stock_diff

0     30
1     50
2    100
Name: Stock, dtype: int64

### Iteration in Pandas
In pandas, iteration refers to looping over rows and columns of a DataFrame or Series. While pandas is optimized for vectorized operations, sometimes we need to loop $\text{---}$ for example, for conditional logic, debugging, or generating complex values.

In [31]:
df = pd.DataFrame({
    'Name' : ['Alice', 'Bob', 'Charlie'],
    'Age' : [25, 30, 35],
    'City' : ['Delhi', 'Mumbai', 'Chennai']
})

In [32]:
df

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   35  Chennai

In [33]:
for index, row in df.iterrows():
    print(f'{index} : {row['Name']} lives in {row['City']} and is {row['Age']} years old.')

0 : Alice lives in Delhi and is 25 years old.
1 : Bob lives in Mumbai and is 30 years old.
2 : Charlie lives in Chennai and is 35 years old.

In [34]:
for row in df.itertuples():
    print(row)
    print(row.Index)
    print(f'{row.Name} lives in {row.City}, and is {row.Age} years old.', end='\n\n')

Pandas(Index=0, Name='Alice', Age=25, City='Delhi')
0
Alice lives in Delhi, and is 25 years old.

Pandas(Index=1, Name='Bob', Age=30, City='Mumbai')
1
Bob lives in Mumbai, and is 30 years old.

Pandas(Index=2, Name='Charlie', Age=35, City='Chennai')
2
Charlie lives in Chennai, and is 35 years old.

In [35]:
# iterate over columns

for col in df.columns:
    print(f'Column : {col}')
    print(df[col].values, end='\n\n')

Column : Name
<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

Column : Age
[25 30 35]

Column : City
<StringArray>
['Delhi', 'Mumbai', 'Chennai']
Length: 3, dtype: str

In [36]:
list(df.columns)

['Name', 'Age', 'City']

In [37]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

### Conditional Example : Add Column with Custom Logic

Based on Age column, I want to create a new column that will classify people as 'young' or 'senior

#### Approach_1 : using loops

In [38]:
# categories = []

# for idx, row in df.iterrows():
#     if (row['Age'] < 40):
#         categories.append('young')
#     else:
#         categories.append('senior')

# df['Category'] = categories

# df.head()

#### Approach_2 : using list comprehension

In [39]:
df['Category'] = ['young' if (age < 40) else 'senior' for age in df['Age']]

df

      Name  Age     City Category
0    Alice   25    Delhi    young
1      Bob   30   Mumbai    young
2  Charlie   35  Chennai    young

#### Approach_3 (Better Way) : Vectorized/Apply

In [40]:
df['Category_vectorized_1'] = df['Age'].apply(lambda age : 'young' if age < 40 else 'senior')

df

      Name  Age     City Category Category_vectorized_1
0    Alice   25    Delhi    young                 young
1      Bob   30   Mumbai    young                 young
2  Charlie   35  Chennai    young                 young

In [41]:
categorize_age_lambda = lambda age : 'young' if age < 40 else 'senior'
df['Category_vectorized_2'] = df['Age'].apply(categorize_age_lambda)

df

      Name  Age     City Category Category_vectorized_1 Category_vectorized_2
0    Alice   25    Delhi    young                 young                 young
1      Bob   30   Mumbai    young                 young                 young
2  Charlie   35  Chennai    young                 young                 young

In [42]:
def categorize_age_function(age):
    # if age < 40:
    #     return 'young'
    # else:
    #     return 'senior'
    return 'young' if age < 40 else 'senior'

df['Category_vectorized_3'] = df['Age'].apply(categorize_age_function)

df

,Name,Age,City,Category,Category_vectorized_1,Category_vectorized_2,Category_vectorized_3
0,Alice,25,Delhi,young,young,young,young
1,Bob,30,Mumbai,young,young,young,young
2,Charlie,35,Chennai,young,young,young,young

In [43]:
def check_if_young_and_delhi(row):
    city = row.City
    age = row.Age

    if city == 'Delhi':
        if age < 40:
            return True
        else:
            return False
    return False


df['If_young_and_from_Delhi'] = df.apply(check_if_young_and_delhi, axis=1)
df

,Name,Age,City,Category,Category_vectorized_1,Category_vectorized_2,Category_vectorized_3,If_young_and_from_Delhi
0,Alice,25,Delhi,young,young,young,young,True
1,Bob,30,Mumbai,young,young,young,young,False
2,Charlie,35,Chennai,young,young,young,young,False

In [44]:
# axis = 0
# keep columns constant and get all rows

# axis = 1
# keep row constant and get all columns

### Sorting in Pandas
Sorting helps you organize your data for better readability, analysis and logical operations $\text{---}$ whether by index or actual data values.

#### Why sorting matters?
You might want to:
- See top-performing products (e.g,, highest sales)
- Order records by name/date
- Prepare data before merging or visualizing

#### Two Main Types of Sorting
1. sort_values() $\rightarrow$ Sort by data values
2. sort_index() $\rightarrow$ Sort by index (row or column labels)

#### 1. sort_values() $\rightarrow$ Sort by data values

##### Syntax:

    DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, na_position='last')

| Argument | Purpose |
| :--- | :--- |
| <span style="color: #F0D392;"> by </span> | column label(s) to sort by |
| <span style="color: #F0D392;"> axis </span> | 0 = rows (default), 1 = columns |
| <span style="color: #F0D392;"> ascending </span> | True = low to high, False = high to low |
| <span style="color: #F0D392;"> inplace </span> | True = modify current object |
| <span style="color: #F0D392;"> na_position </span> | 'first' or 'last' for NaNs |

In [45]:
# Example of inplace

class Cal:
    def __init__(self, a):
        self.a = a

    def add(self, b):
        c = self.a + b
        return c

    def inplace_add(self, b):
        self.a += b
        return self.a

In [46]:
c_cal = Cal(10)

In [47]:
c_cal.a

10

In [48]:
c_cal.add(10)

20

In [49]:
c_cal.a

10

In [50]:
c_cal.a = c_cal.add(10)     # inplace=False

In [51]:
c_cal.a

20

In [52]:
c_cal.inplace_add(10)       # inplace=True

30

In [53]:
c_cal.a

30

In [54]:
df = pd.read_csv(titanic_dataset_github_url)

In [55]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [56]:
sorted_df = df.sort_values('Age')
sorted_df[['Name', 'Age']].head(5)

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
644           Baclini, Miss. Eugenie  0.75
469    Baclini, Miss. Helene Barbara  0.75
78     Caldwell, Master. Alden Gates  0.83

In [57]:
sorted_df[['Name', 'Age']].head(10)

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
644           Baclini, Miss. Eugenie  0.75
469    Baclini, Miss. Helene Barbara  0.75
78     Caldwell, Master. Alden Gates  0.83
831  Richards, Master. George Sibley  0.83
305   Allison, Master. Hudson Trevor  0.92
827            Mallet, Master. Andre  1.00
381      Nakid, Miss. Maria ("Mary")  1.00
164     Panula, Master. Eino Viljami  1.00

In [58]:
sorted_df[['Name', 'Age']].tail(10)

                                             Name  Age
832                                Saad, Mr. Amin  NaN
837                           Sirota, Mr. Maurice  NaN
839                          Marechal, Mr. Pierre  NaN
846                      Sage, Mr. Douglas Bullen  NaN
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  NaN
859                              Razi, Mr. Raihed  NaN
863             Sage, Miss. Dorothy Edith "Dolly"  NaN
868                   van Melkebeke, Mr. Philemon  NaN
878                            Laleff, Mr. Kristo  NaN
888      Johnston, Miss. Catherine Helen "Carrie"  NaN

In [59]:
sorted_df.iloc[200:300, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S
391,392,1,3,"Jansson, Mr. Carl Olof",male,21.0,0,0,350034,7.7958,NaN,S
120,121,0,2,"Hickman, Mr. Stanley George",male,21.0,2,0,S.O.C. 14879,73.5000,NaN,S
588,589,0,3,"Gilinski, Mr. Eliezer",male,22.0,0,0,14973,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
693,694,0,3,"Saad, Mr. Khalil",male,25.0,0,0,2672,7.2250,NaN,C
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
703,704,0,3,"Gallagher, Mr. Martin",male,25.0,0,0,36864,7.7417,NaN,Q
785,786,0,3,"Harmer, Mr. Abraham (David Lishin)",male,25.0,0,0,374887,7.2500,NaN,S

In [60]:
print(df['Age'].dtype)

float64

In [61]:
df['Age'] = df['Age'].astype('int64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [62]:
df['Age'] = df['Age'].fillna(0).astype('int64')

In [63]:
df[['Name', 'Age']].tail(10)

                                         Name  Age
881                        Markun, Mr. Johann   33
882              Dahlberg, Miss. Gerda Ulrika   22
883             Banfield, Mr. Frederick James   28
884                    Sutehall, Mr. Henry Jr   25
885      Rice, Mrs. William (Margaret Norton)   39
886                     Montvila, Rev. Juozas   27
887              Graham, Miss. Margaret Edith   19
888  Johnston, Miss. Catherine Helen "Carrie"    0
889                     Behr, Mr. Karl Howell   26
890                       Dooley, Mr. Patrick   32

In [64]:
sorted_df = df.sort_values('Age')
sorted_df[['Name', 'Age']].tail(10)

                                     Name  Age
280                      Duane, Mr. Frank   65
54         Ostby, Mr. Engelhart Cornelius   65
33                  Wheadon, Mr. Edward H   66
672           Mitchell, Mr. Henry Michael   70
745          Crosby, Capt. Edward Gifford   70
116                  Connors, Mr. Patrick   70
493               Artagaveytia, Mr. Ramon   71
96              Goldschmidt, Mr. George B   71
851                   Svensson, Mr. Johan   74
630  Barkworth, Mr. Algernon Henry Wilson   80

##### Example 2: Sort by multiple columns
First sort by Pclass (ascending), then by Fare (descending)

In [65]:
df_sorted = df.sort_values(by=['Pclass', 'Fare'], ascending=[True, False])

In [66]:
df_sorted.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64,1,4,19950,263.0000,C23 C25 C27,S
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24,0,1,PC 17558,247.5208,B58 B60,C

#### 2. sort_index() $\rightarrow$ Sort by index (row or column labels)
This is useful when you've used a meaningful index and want to restore or arrange it.

    DataFrame.sort_index(axis=0, ascending=True, inplace=False)
axis=0 $\rightarrow$ Sort rows

axis=1 $\rightarrow$ Sort columns

In [67]:
df_sort_2 = df.set_index('PassengerId')
df_sorted_by_index = df_sort_2.sort_index()

In [68]:
df_sorted_by_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

#### Sorting Columns Alphabetically

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [70]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [71]:
df[['Ticket', 'Name']]

               Ticket                                               Name
0           A/5 21171                            Braund, Mr. Owen Harris
1            PC 17599  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    STON/O2. 3101282                             Heikkinen, Miss. Laina
3              113803       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              373450                           Allen, Mr. William Henry
..                ...                                                ...
886            211536                              Montvila, Rev. Juozas
887            112053                       Graham, Miss. Margaret Edith
888        W./C. 6607           Johnston, Miss. Catherine Helen "Carrie"
889            111369                              Behr, Mr. Karl Howell
890            370376                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [72]:
sorted(df.columns)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'Ticket']

In [73]:
df_sorted = df[sorted(df.columns)]

In [74]:
df_sorted.head()

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

### Working with Text Data in Pandas

In [75]:
# lowercase
df['Name'].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [76]:
# UPPERCASE
df['Name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [77]:
# Capitalize
df['Name'].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [78]:
# Title Case
df['Name'].str.title()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [79]:
# string length
df['Name'].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64